## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
0,0,Punta Arenas,-53.1500,-70.9167,59.00,67,90,14.97,CL,light rain
1,1,Yellowknife,62.4560,-114.3525,-4.00,77,40,10.36,CA,light snow
2,2,Peniche,39.3558,-9.3811,46.00,73,0,5.99,PT,clear sky
3,3,Marsh Harbour,26.5412,-77.0636,67.75,63,51,21.74,BS,broken clouds
4,4,Butaritari,3.0707,172.7902,80.91,75,50,20.92,KI,scattered clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 95

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
4,4,Butaritari,3.0707,172.7902,80.91,75,50,20.92,KI,scattered clouds
5,5,Rikitea,-23.1203,-134.9692,78.21,67,19,3.85,PF,few clouds
6,6,Alofi,-19.0595,-169.9187,84.20,79,40,6.91,NU,scattered clouds
8,8,Cidreira,-30.1811,-50.2056,75.25,94,91,4.90,BR,light rain
11,11,Arica,-18.4750,-70.3042,77.00,47,0,16.11,CL,clear sky
13,13,Cabo San Lucas,22.8909,-109.9124,79.00,41,1,9.22,MX,clear sky
16,16,Vaini,-21.2000,-175.2000,82.40,89,40,8.05,TO,light rain
20,20,Axim,4.8699,-2.2405,79.54,83,96,8.59,GH,overcast clouds
21,21,Hambantota,6.1241,81.1185,76.33,86,100,8.90,LK,overcast clouds
23,23,Puerto Ayora,-0.7393,-90.3518,80.60,74,40,13.80,EC,scattered clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                268
City                   268
Lat                    268
Lng                    268
Max Temp               268
Humidity               268
Cloudiness             268
Wind Speed             268
Country                266
Current Description    268
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Current Description
4,4,Butaritari,3.0707,172.7902,80.91,75,50,20.92,KI,scattered clouds
5,5,Rikitea,-23.1203,-134.9692,78.21,67,19,3.85,PF,few clouds
6,6,Alofi,-19.0595,-169.9187,84.20,79,40,6.91,NU,scattered clouds
8,8,Cidreira,-30.1811,-50.2056,75.25,94,91,4.90,BR,light rain
11,11,Arica,-18.4750,-70.3042,77.00,47,0,16.11,CL,clear sky
...,...,...,...,...,...,...,...,...,...,...
671,671,Am Timan,11.0297,20.2827,74.70,20,0,4.23,TD,clear sky
676,676,Champerico,14.3000,-91.9167,91.40,14,40,9.22,GT,scattered clouds
686,686,San Cristobal,7.7669,-72.2250,86.00,54,40,10.36,VE,scattered clouds
687,687,Labuhan,-6.8844,112.2051,78.13,83,100,5.26,ID,light rain
693,693,Payo,-3.7508,103.6372,71.94,93,100,1.59,ID,overcast clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Butaritari,KI,80.91,scattered clouds,3.0707,172.7902,
5,Rikitea,PF,78.21,few clouds,-23.1203,-134.9692,
6,Alofi,NU,84.20,scattered clouds,-19.0595,-169.9187,
8,Cidreira,BR,75.25,light rain,-30.1811,-50.2056,
11,Arica,CL,77.00,clear sky,-18.4750,-70.3042,
13,Cabo San Lucas,MX,79.00,clear sky,22.8909,-109.9124,
16,Vaini,TO,82.40,light rain,-21.2000,-175.2000,
20,Axim,GH,79.54,overcast clouds,4.8699,-2.2405,
21,Hambantota,LK,76.33,overcast clouds,6.1241,81.1185,
23,Puerto Ayora,EC,80.60,scattered clouds,-0.7393,-90.3518,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
    
hotel_df.head(10)

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Butaritari,KI,80.91,scattered clouds,3.0707,172.7902,Isles Sunset Lodge
5,Rikitea,PF,78.21,few clouds,-23.1203,-134.9692,Pension Maro'i
6,Alofi,NU,84.20,scattered clouds,-19.0595,-169.9187,Taloa Heights
8,Cidreira,BR,75.25,light rain,-30.1811,-50.2056,Hotel Castelo
11,Arica,CL,77.00,clear sky,-18.4750,-70.3042,Hostal Jardin Del Sol
13,Cabo San Lucas,MX,79.00,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
16,Vaini,TO,82.40,light rain,-21.2000,-175.2000,Keleti Beach Resort
20,Axim,GH,79.54,overcast clouds,4.8699,-2.2405,AXIM BEACH RESORT AND SPA
21,Hambantota,LK,76.33,overcast clouds,6.1241,81.1185,Bungalow 63
23,Puerto Ayora,EC,80.60,scattered clouds,-0.7393,-90.3518,Castillo Galapagos

In [12]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Butaritari,KI,80.91,scattered clouds,3.0707,172.7902,Isles Sunset Lodge
5,Rikitea,PF,78.21,few clouds,-23.1203,-134.9692,Pension Maro'i
6,Alofi,NU,84.20,scattered clouds,-19.0595,-169.9187,Taloa Heights
8,Cidreira,BR,75.25,light rain,-30.1811,-50.2056,Hotel Castelo
11,Arica,CL,77.00,clear sky,-18.4750,-70.3042,Hostal Jardin Del Sol
13,Cabo San Lucas,MX,79.00,clear sky,22.8909,-109.9124,Hotel Tesoro Los Cabos
16,Vaini,TO,82.40,light rain,-21.2000,-175.2000,Keleti Beach Resort
20,Axim,GH,79.54,overcast clouds,4.8699,-2.2405,AXIM BEACH RESORT AND SPA
21,Hambantota,LK,76.33,overcast clouds,6.1241,81.1185,Bungalow 63
23,Puerto Ayora,EC,80.60,scattered clouds,-0.7393,-90.3518,Castillo Galapagos

In [17]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_Vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [14]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country Code</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temperature</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))